export const priceList = [
    {
        id: 'drycleaning',
        label: 'Dry Cleaning',
        hasSteamIron: true,
        items: [
            { name: 'Anarkali ( Regular )', price: 350, steam: 80 },
            { name: 'Anarkali ( Light work )', price: 450, steam: 110 },
            { name: 'Anarkali ( Party wear )', price: 550, steam: 250 },
            { name: 'Bed Cover / Bedsheet ( Single )', price: 280, steam: 110 },
            { name: 'Bed Cover / Bedsheet ( Double )', price: 330, steam: 150 },
            { name: 'Blanket / Quilt ( Single )', price: 350, steam: null },
            { name: 'Blanket / Quilt ( Double )', price: 450, steam: null },
            { name: 'Bra / Inner', price: 99, steam: null },
            { name: 'Blouse', price: 99, steam: 40 },
            { name: 'Blouse ( Party wear )', price: 150, steam: 60 },
            { name: 'Blazer / Coat', price: 250, steam: 120 },
            { name: 'Blazer / Coat ( Party wear )', price: 350, steam: 160 },
            { name: 'Curtain Net ( per Sq. Ft. )', price: 10, steam: 4 },
            { name: 'Curtain Single lining ( per Sq. Ft. )', price: 12, steam: 4 },
            { name: 'Curtain Double lining ( per Sq. Ft. )', price: 15, steam: 6 },
            { name: 'Cushion / Pillow Cover ( Regular )', price: 70, steam: 35 },
            { name: 'Cushion / Pillow Cover ( Large )', price: 110, steam: 35 },
            { name: 'Carpet ( Per Square Ft. )', price: 40, steam: null },
            { name: 'Cargo Trouser', price: 160, steam: 40 },
            { name: 'Cargo Jeans', price: 160, steam: 40 },
            { name: 'Dhoti', price: 160, steam: 40 },
            { name: 'Dhoti ( Party wear )', price: 220, steam: 60 },
            { name: 'Dress ( Short )', price: 180, steam: 35 },
            { name: 'Dress ( Long )', price: 220, steam: 50 },
            { name: 'Dress ( Long Party wear )', price: 320, steam: 90 },
            { name: 'Dupatta / Stole', price: 110, steam: 35 },
            { name: 'Dupatta / Stole ( Party wear )', price: 150, steam: 55 },
            { name: 'Gowns ( Regular )', price: 350, steam: 150 },
            { name: 'Gowns ( Party wear )', price: 450, steam: 200 },
            { name: 'Hat / Cap', price: 120, steam: null },
            { name: 'Hoodie', price: 150, steam: 35 },
            { name: 'Jacket ( Formal )', price: 150, steam: 40 },
            { name: 'Jacket ( Winter )', price: 180, steam: null },
            { name: 'Jacket ( Leather )', price: 350, steam: null },
            { name: 'Jeans', price: 140, steam: 35 },
            { name: 'Jump Suit', price: 350, steam: 60 },
            { name: "Kid's wear ( Regular )", price: 99, steam: 25 },
            { name: "Kid's wear ( Party wear )", price: 210, steam: 35 },
            { name: 'Kurta ( Short )', price: 110, steam: 35 },
            { name: 'Kurta ( Long )', price: 150, steam: 40 },
            { name: 'Kurta ( Silk )', price: 180, steam: 50 },
            { name: 'Kurta ( Party wear )', price: 250, steam: 70 },
            { name: 'Leggings', price: 110, steam: 35 },
            { name: 'Lehenga ( Regular )', price: 450, steam: 150 },
            { name: 'Lehenga ( Light work )', price: 550, steam: 200 },
            { name: 'Lehenga ( Party wear )', price: 600, steam: 300 },
            { name: 'Over Coat', price: 350, steam: 150 },
            { name: 'Plazo', price: 120, steam: 40 },
            { name: 'Plazo ( Party wear )', price: 160, steam: 60 },
            { name: 'Petticoat ( Regular )', price: 110, steam: 35 },
            { name: 'Petticoat ( Silk )', price: 150, steam: 45 },
            { name: 'Pyajama', price: 110, steam: 35 },
            { name: 'Razai ( Single )', price: 350, steam: null },
            { name: 'Razai ( Double )', price: 450, steam: null },
            { name: 'Rug ( Small )', price: 350, steam: null },
            { name: 'Rug ( Medium )', price: 450, steam: null },
            { name: 'Salwar', price: 120, steam: 35 },
            { name: 'Saree ( Cotton )', price: 300, steam: 80 },
            { name: 'Saree ( Silk )', price: 350, steam: 150 },
            { name: 'Saree ( Party wear )', price: 400, steam: 200 },
            { name: 'Shawl', price: 180, steam: 60 },
            { name: 'Sherwani ( Regular )', price: 300, steam: 150 },
            { name: 'Sherwani ( Light work )', price: 450, steam: 200 },
            { name: 'Sherwani ( Designer )', price: 600, steam: 300 },
            { name: 'Shirt', price: 110, steam: 35 },
            { name: 'Shirt ( Party wear )', price: 150, steam: 50 },
            { name: 'Shirt ( Valvate )', price: 180, steam: 60 },
            { name: 'Shirt ( Leather )', price: 300, steam: null },
            { name: "Short's", price: 99, steam: 35 },
            { name: 'Skirt ( Short )', price: 99, steam: 35 },
            { name: 'Skirt ( Long )', price: 150, steam: 35 },
            { name: 'Sofa Cover ( Single Seater )', price: 180, steam: 80 },
            { name: 'Sofa Cover ( Double Seater )', price: 280, steam: 90 },
            { name: 'Sofa Cover ( Three Seater )', price: 360, steam: 150 },
            { name: 'Suit ( 2 pcs )', price: 320, steam: 150 },
            { name: 'Suit ( 3 pcs )', price: 480, steam: 200 },
            { name: 'Sweater', price: 180, steam: 60 },
            { name: 'Sweatshirt', price: 150, steam: 35 },
            { name: 'T-Shirt', price: 110, steam: 35 },
            { name: 'Table Mate ( Regular )', price: 150, steam: 35 },
            { name: 'Table Mate ( Large )', price: 300, steam: 50 },
            { name: 'Tie', price: 60, steam: 35 },
            { name: 'Top', price: 110, steam: 35 },
            { name: 'Top ( Long )', price: 150, steam: 40 },
            { name: 'Top ( Party wear )', price: 180, steam: 60 },
            { name: 'Towel ( Regular )', price: 80, steam: null },
            { name: 'Towel ( Large )', price: 150, steam: null },
            { name: 'Toy ( Small )', price: 200, steam: null },
            { name: 'Toy ( Large )', price: 350, steam: null },
            { name: 'Track Pant', price: 140, steam: 35 },
            { name: 'Trouser', price: 140, steam: 35 },
            { name: 'Trouser ( Valvate )', price: 200, steam: 90 },
            { name: 'Trouser ( Leather )', price: 350, steam: null },
            { name: 'Underwear / Panties', price: 60, steam: null },
            { name: 'Vest ( Inner )', price: 99, steam: 35 },
            { name: 'Waist Coat', price: 250, steam: 80 },
            { name: 'Waist Coat ( Party wear )', price: 400, steam: 130 },
        ],
    },
    {
        id: 'laundry',
        label: 'Laundry by Kilo',
        hasSteamIron: false,
        items: [
            { name: 'Wash & Fold', price: 150 },
            { name: 'Wash & Iron', price: 180 },
        ],
    },
    {
        id: 'steam-iron',
        label: 'Steam Iron',
        hasSteamIron: false,
        items: [
            { name: 'Steam Iron', price: 35 },
            { name: 'Anarkali ( Regular )', price: 80 },
            { name: 'Anarkali ( Light Work )', price: 110 },
            { name: 'Anarkali ( Party wear )', price: 250 },
            { name: 'Bed Cover / Bedsheet ( Single )', price: 110 },
            { name: 'Bed Cover / Bedsheet ( Double )', price: 150 },
            { name: 'Blouse', price: 40 },
            { name: 'Blouse ( Party wear )', price: 60 },
            { name: 'Blazer / Coat', price: 120 },
            { name: 'Blazer / Coat ( Party wear )', price: 160 },
            { name: 'Curtain Net ( per Sq. Ft. )', price: 4 },
            { name: 'Curtain Single lining ( per Sq. Ft. )', price: 4 },
            { name: 'Curtain Double lining ( per Sq. Ft. )', price: 6 },
            { name: 'Cushion / Pillow Cover ( Regular )', price: 35 },
            { name: 'Cushion / Pillow Cover ( Large )', price: 35 },
            { name: 'Cargo Trouser', price: 40 },
            { name: 'Cargo Jeans', price: 40 },
            { name: 'Dhoti', price: 40 },
            { name: 'Dhoti ( Party wear )', price: 60 },
            { name: 'Dress ( Short )', price: 35 },
            { name: 'Dress ( Long )', price: 50 },
            { name: 'Dress ( Long Party wear )', price: 90 },
            { name: 'Dupatta / Stole', price: 35 },
            { name: 'Dupatta / Stole ( Party wear )', price: 55 },
            { name: 'Gowns ( Regular )', price: 150 },
            { name: 'Gowns ( Party wear )', price: 200 },
            { name: 'Hoodie', price: 35 },
            { name: 'Jacket ( Formal )', price: 40 },
            { name: 'Jeans', price: 40 },
            { name: 'Jump Suit', price: 60 },
            { name: "Kid's wear ( Regular )", price: 25 },
            { name: "Kid's wear ( Party wear )", price: 35 },
            { name: 'Kurta ( Short )', price: 35 },
            { name: 'Kurta ( Long )', price: 40 },
            { name: 'Kurta ( Silk )', price: 50 },
            { name: 'Kurta ( Party wear )', price: 70 },
            { name: 'Leggings', price: 35 },
            { name: 'Lehenga ( Regular )', price: 150 },
            { name: 'Lehenga ( Light work )', price: 200 },
            { name: 'Lehenga ( Party wear )', price: 300 },
            { name: 'Over Coat', price: 150 },
            { name: 'Plazo', price: 40 },
            { name: 'Plazo ( Party wear )', price: 60 },
            { name: 'Petticoat ( Regular )', price: 35 },
            { name: 'Petticoat ( Silk )', price: 45 },
            { name: 'Pyajama', price: 35 },
            { name: 'Salwar', price: 35 },
            { name: 'Saree ( Cotton )', price: 80 },
            { name: 'Saree ( Silk )', price: 150 },
            { name: 'Saree ( Party wear )', price: 200 },
            { name: 'Shawl', price: 60 },
            { name: 'Sherwani ( Regular )', price: 150 },
            { name: 'Sherwani ( Light work )', price: 200 },
            { name: 'Sherwani ( Designer )', price: 300 },
            { name: 'Shirt', price: 35 },
            { name: 'Shirt ( Party wear )', price: 50 },
            { name: 'Shirt ( Valvate )', price: 60 },
            { name: "Short's", price: 35 },
            { name: 'Skirt ( Short )', price: 35 },
            { name: 'Skirt ( Long )', price: 35 },
            { name: 'Sofa Cover ( Single Seater )', price: 80 },
            { name: 'Sofa Cover ( Double Seater )', price: 90 },
            { name: 'Sofa Cover ( Three Seater )', price: 150 },
            { name: 'Suit ( 2 pcs )', price: 150 },
            { name: 'Suit ( 3 pcs )', price: 200 },
            { name: 'Sweater', price: 60 },
            { name: 'Sweatshirt', price: 35 },
            { name: 'T-Shirt', price: 35 },
            { name: 'Table Mate ( Regular )', price: 35 },
            { name: 'Table Mate ( Large )', price: 50 },
            { name: 'Tie', price: 35 },
            { name: 'Top', price: 35 },
            { name: 'Top ( Long )', price: 40 },
            { name: 'Top ( Party wear )', price: 60 },
            { name: 'Trouser', price: 35 },
            { name: 'Track pant', price: 35 },
            { name: 'Trouser(Valvate)', price: 90 },
            { name: 'Vest (Inner)', price: 35 },
            { name: 'Waist Coat', price: 80 },
            { name: 'Waist Coat ( Party wear )', price: 130 },
        ],
    },
    {
        id: 'accessories',
        label: 'Accessories',
        hasSteamIron: false,
        items: [
            { name: 'Laptop Bag Regular', price: 450 },
            { name: 'Laptop Bag Leather', price: 550 },
            { name: 'Flipflops', price: 250 },
            { name: 'Shoe ( Sports )', price: 450 },
            { name: 'Shoe ( Sued )', price: 550 },
            { name: 'Shoe ( Leather )', price: 550 },
        ],
    },
]
